[package]
name = "publish"
version = "0.0.0"
edition = "2018"
publish = false

[dependencies]
cargo_metadata = "0.14.0"
cradle = "0.0.21"
clap = { version = "4.4.4", features = ["derive"] }
tempfile = "3.2.0"
